services:
  postgres:
    image: postgres:16
    mem_limit: 384m
    env_file:
      - .env
    command: ["postgres", "-c", "shared_buffers=128MB"]
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]

  mongo:
    image: mongo:7
    mem_limit: 384m
    command: ["mongod", "--wiredTigerCacheSizeGB", "0.25"]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand(ping)"]

  redis:
    image: redis:7
    mem_limit: 128m
    command:
      [
        "redis-server",
        "--maxmemory",
        "100mb",
        "--maxmemory-policy",
        "noeviction",
      ]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

  rabbitmq:
    image: rabbitmq:3-management
    mem_limit: 512m
    environment:
      - RABBITMQ_VM_MEMORY_HIGH_WATERMARK=0.6
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]

volumes:
  postgres_data:
