spring.application.name=ms-email

# RabbitMQ
spring.rabbitmq.host=${RABBIT_HOST:rabbitmq}
spring.rabbitmq.port=${RABBIT_PORT:5672}
spring.rabbitmq.username=${RABBIT_USER:guest}
spring.rabbitmq.password=${RABBIT_PASS:guest}

# Configurações do SMTP
spring.mail.host=${MAIL_HOST:sandbox.smtp.mailtrap.io}
spring.mail.port=${MAIL_PORT:2525}
spring.mail.username=${MAIL_USER:seu_usuario}
spring.mail.password=${MAIL_PASS:sua_senha}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true